---
driver:
  name: docker
  provision_command: curl -L http://www.chef.io/chef/install.sh | bash

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[delivery-truck::default]
    attributes:
